// CREATE TABLE recipes (
//   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//   img VARCHAR(300) NOT NULL,
//   link VARCHAR(300) NOT NULL,
//   name VARCHAR(50) NOT NULL
// );
// --change the link name--
// CREATE TABLE ingredients (
//   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//   name VARCHAR(80) NOT NULL
// );

// CREATE TABLE ingredient_types (
//   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//   name VARCHAR(20) NOT NULL
// );

// CREATE TABLE recipes_ingredients_types (
//   PRIMARY KEY (recipe_id, ingredient_id, ingredient_type_id),
//   recipe_id INT REFERENCES recipes (id),
//   ingredient_id INT REFERENCES ingredients (id),
//   ingredient_type_id INT REFERENCES ingredient_types (id)

// );

// --Insterts--

// INSERT INTO recipes
//   (name, img, link)
// VALUES
//   ('Carbonara','https://images.unsplash.com/photo-1588013273468-315fd88ea34c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80', 'https://www.bonappetit.com/recipe/simple-carbonara'),
//   ('Shakshuka','https://images.unsplash.com/photo-1590412200988-a436970781fa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80', 'https://toriavey.com/toris-kitchen/shakshuka/'),
//   ('Chilli con Carne','https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=631&q=80', 'https://www.food24.com/recipe/cheats-5-ingredient-chilli-con-carne/'),
//   ('Sweet Potato Curry','https://images.unsplash.com/photo-1590412200988-a436970781fa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80', 'https://www.eatingbirdfood.com/5-ingredient-sweet-potato-curry/');

// INSERT INTO ingredients
//   (name)
// VALUES
//   ('bacon'),
//   ('parmesan'),
//   ('egg'),
//   ('pasta'),
//   ('onion'),
//   ('canned tomatos'),
//   ('garlic'),
//   ('cumin'),
//   ('chilli'),
//   ('minced meat'),
//   ('beans'),
//   ('smoked paprika'),
//   ('marjoram'),
//   ('curry-paste'),
//   ('coconut milk'),
//   ('sweet potato'),
//   ('lime'),
//   ('ginger')
//   ;

// INSERT INTO ingredient_types
//   (name)
// VALUES
//   ('main'),
//   ('spices');

// INSERT INTO recipes_ingredients_types
//   (recipe_id, ingredient_id, ingredient_type_id)
// VALUES
//   (1, 1, 1),
//   (1, 2, 1),
//   (1, 3, 1),
//   (1, 4, 1),
//   (2, 5, 1),
//   (2, 3, 1),
//   (2, 6, 1),
//   (2, 7, 2),
//   (2, 8, 2),
//   (2, 9, 2),
//   (3, 10, 1),
//   (3, 11, 1),
//   (3, 5, 1),
//   (3, 6, 1),
//   (3, 9, 2),
//   (3, 8, 2),
//   (3, 12, 2),
//   (3, 7, 2),
//   (4, 5, 1),
//   (4, 14, 1),
//   (4, 15, 1),
//   (4, 16, 1),
//   (4, 17, 2),
//   (4, 18, 2),
//   (4, 7, 2)
//   ;

// -- Recepies and ing of all action films
// SELECT
//   recipes.id as recipe_id,
//   recipes.name as recipe_name,
//   recipes.img as recipe_img,
//   recipes.link as recipe_link,
//   ingredients.id as ingredient_id,
//   ingredients.name as ingredient_name
// FROM
//   recipes,
//   ingredients,
//   ingredient_types,
//   recipes_ingredients_types
// WHERE
//   ingredient_types.name = 'main' AND
//   recipes_ingredients_types.ingredient_type_id = ingredient_types.id AND
//   recipes_ingredients_types.recipe_id = recipes.id AND
//   recipes_ingredients_types.ingredient_id = ingredients.id;
// psql  -d d6bo5odafihlg2 -U ssguzktqivwkki -h ec2-52-212-157-46.eu-west-1.compute.amazonaws.com

// insert into users (user_name, password_hash, user_role_id) Values('Paul Schnetzer', '$argon2i$v=19$m=4096,t=3,p=1$WRmp6TQADwNi7T2ihlHhww$t+ExNtJfB2PREHW/3RVAsVteg3e4MxmsYVPRjkew4N0', '1')
